package clase;

public class Girafa extends Animal {
    public Girafa(String nume)
    {
        super(nume);
        //todo auto generated constructor strub
    }
    @Override
    public void mananca(String mancare){
        //todo autogenerated method stub
        System.out.print("Zebra "+this.getNume()+ " mananca"+mancare);
    }
}
